[project]
authors = ["Stefan Ionescu"]
entry = "main.sw"
license = "Apache-2.0"
name = "constant_product_factory_contract"

[dependencies]
abi_core                     = { path = "../../../../abis/abi_core" }
constant_product_factory_abi = { path = "../factory_abi" }
