[project]
authors = ["Stefan Ionescu"]
entry = "main.sw"
license = "Apache-2.0"
name = "router_contract"

[dependencies]
abi_core            = { path = "../../abis/abi_core" }
abi_utils           = { path = "../../abis/abi_utils" }
router_abi          = { path = "../router_abi" }
factory_registry_abi = { path = "../../factory_registry/factory_registry_abi" }
