[project]
authors = ["Stefan Ionescu"]
entry = "main.sw"
license = "Apache-2.0"
name = "factory_registry_contract"

[dependencies]
abi_core            = { path = "../../abis/abi_core" }
factory_registry_abi = { path = "../factory_registry_abi" }
